/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 34fbcae2e5dc48c291f68fcfb6859ce8)
interface __BaseEnv_CloudflareBindings {
	CONTENT_DB: D1Database;
	AI_RATE_LIMITER: RateLimit;
	ADMIN_RATE_LIMITER: RateLimit;
	BASE_URL: string;
	API_KEY: string;
	MODEL: string;
	AI_PROTOCOL: string;
	ADMIN_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface ProductionEnv {
		CONTENT_DB: D1Database;
		AI_RATE_LIMITER: RateLimit;
		ADMIN_RATE_LIMITER: RateLimit;
		BASE_URL: string;
		API_KEY: string;
		MODEL: string;
		AI_PROTOCOL: string;
		ADMIN_SESSION_SECRET: string;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BASE_URL" | "API_KEY" | "MODEL" | "AI_PROTOCOL" | "ADMIN_SESSION_SECRET">> {}
}
