/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 869a63051d3bccc2e6ef15eabc836df1)
interface __BaseEnv_CloudflareBindings {
	CONTENT_DB: D1Database;
	AI_RATE_LIMITER: RateLimit;
	ADMIN_RATE_LIMITER: RateLimit;
	REPORT_RATE_LIMITER: RateLimit;
	TASK_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
	BASE_URL: string;
	API_KEY: string;
	MODEL: string;
	AI_PROTOCOL: string;
	ADMIN_SESSION_SECRET: string;
	QUESTION_TASK_WORKFLOW: Workflow<Parameters<import("./worker/index").QuestionTaskWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface ProductionEnv {
		CONTENT_DB: D1Database;
		AI_RATE_LIMITER: RateLimit;
		ADMIN_RATE_LIMITER: RateLimit;
		REPORT_RATE_LIMITER: RateLimit;
		TASK_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		BASE_URL: string;
		API_KEY: string;
		MODEL: string;
		AI_PROTOCOL: string;
		ADMIN_SESSION_SECRET: string;
		QUESTION_TASK_WORKFLOW: Workflow<Parameters<import("./worker/index").QuestionTaskWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BASE_URL" | "API_KEY" | "MODEL" | "AI_PROTOCOL" | "ADMIN_SESSION_SECRET">> {}
}
