/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 5ec47fcf0ca2f519d5d12221aaadaa06)
interface __BaseEnv_CloudflareBindings {
	AI_RATE_LIMITER: RateLimit;
	AI_BASE_URL: "https://api.deepseek.com";
	AI_MODEL: "deepseek-chat";
	AI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_BASE_URL" | "AI_MODEL" | "AI_API_KEY">> {}
}
