import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

interface SeedQuestion {
  id: string;
  kp_id: string;
  kp_name: string;
  grade: string;
  semester: string;
  difficulty: 'easy' | 'medium' | 'hard';
  type?: 'fill_blank' | 'choice' | 'mixed';
  question: string;
  blanks: string[];
  blank_types?: string[];
  choices?: Array<{ label: string; content: string }>;
  correctChoice?: string;
  solution: string;
  common_mistake: string;
  hint: string;
  enable?: boolean;
  checkMessage?: string;
}

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEFAULT_INPUT = path.join(ROOT, 'data/questions.seed.json');
const DEFAULT_OUTPUT = path.join(ROOT, '.wrangler/question-bank-seed.sql');

function sqlValue(value: string | null): string {
  if (value === null) return 'NULL';
  return `'${value.replaceAll("'", "''")}'`;
}

function jsonValue(value: unknown[] | undefined): string {
  return value === undefined ? 'NULL' : sqlValue(JSON.stringify(value));
}

function normalizeType(question: SeedQuestion): 'fill_blank' | 'choice' | 'mixed' {
  if (question.type) return question.type;
  return question.choices?.length ? 'choice' : 'fill_blank';
}

function assertSeedQuestion(value: unknown, index: number): asserts value is SeedQuestion {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`Question at index ${index} must be an object`);
  }
  const question = value as Partial<SeedQuestion>;
  for (const key of [
    'id',
    'kp_id',
    'kp_name',
    'grade',
    'semester',
    'difficulty',
    'question',
    'solution',
    'common_mistake',
    'hint',
  ] as const) {
    if (typeof question[key] !== 'string' || !question[key]) {
      throw new Error(`Question at index ${index} has an invalid ${key}`);
    }
  }
  if (!Array.isArray(question.blanks)) {
    throw new Error(`Question at index ${index} has invalid blanks`);
  }
}

export function buildQuestionBankSeedSql(raw: string): {
  sql: string;
  hash: string;
  total: number;
  enabled: number;
} {
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) throw new Error('Question data must be an array');
  parsed.forEach(assertSeedQuestion);
  const questions = parsed as SeedQuestion[];
  const hash = createHash('sha256').update(raw).digest('hex');
  const enabled = questions.filter(question => question.enable !== false).length;
  const statements = [
    '-- Generated by scripts/seedQuestionBank.ts. Do not commit this file.',
    'PRAGMA foreign_keys = ON;',
  ];
  const insertPrefix = `INSERT OR IGNORE INTO questions
  (id, kp_id, kp_name, grade, semester, difficulty, type, question, blanks_json,
   blank_types_json, choices_json, correct_choice, solution, common_mistake, hint,
   enable, check_message)
VALUES\n`;
  let valueRows: string[] = [];
  let currentStatementLength = insertPrefix.length;

  const flushRows = () => {
    if (valueRows.length === 0) return;
    statements.push(`${insertPrefix}${valueRows.join(',\n')};`);
    valueRows = [];
    currentStatementLength = insertPrefix.length;
  };

  for (const question of questions) {
    const values = [
      sqlValue(question.id),
      sqlValue(question.kp_id),
      sqlValue(question.kp_name),
      sqlValue(question.grade),
      sqlValue(question.semester),
      sqlValue(question.difficulty),
      sqlValue(normalizeType(question)),
      sqlValue(question.question),
      sqlValue(JSON.stringify(question.blanks)),
      jsonValue(question.blank_types),
      jsonValue(question.choices),
      sqlValue(question.correctChoice ?? null),
      sqlValue(question.solution),
      sqlValue(question.common_mistake),
      sqlValue(question.hint),
      question.enable === false ? '0' : '1',
      sqlValue(question.checkMessage ?? null),
    ];
    const row = `(${values.join(', ')})`;
    if (valueRows.length > 0 && currentStatementLength + row.length > 12_000) flushRows();
    valueRows.push(row);
    currentStatementLength += row.length + 2;
  }
  flushRows();

  statements.push(
    `INSERT OR IGNORE INTO published_questions
  (id, kp_id, kp_name, grade, semester, difficulty, type, question, blanks_json,
   blank_types_json, choices_json, correct_choice, solution, common_mistake, hint,
   enable, check_message, published_revision, published_at)
SELECT id, kp_id, kp_name, grade, semester, difficulty, type, question, blanks_json,
  blank_types_json, choices_json, correct_choice, solution, common_mistake, hint,
  enable, check_message, 1, CURRENT_TIMESTAMP
FROM questions
WHERE (SELECT published_revision FROM question_bank_meta WHERE singleton_id = 1) = 0;`,
    `UPDATE question_bank_meta
SET draft_revision = CASE WHEN draft_revision = 0 THEN 1 ELSE draft_revision END,
    published_revision = CASE WHEN published_revision = 0 THEN 1 ELSE published_revision END,
    source_sha256 = COALESCE(source_sha256, ${sqlValue(hash)}),
    imported_at = COALESCE(imported_at, CURRENT_TIMESTAMP),
    published_at = COALESCE(published_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE singleton_id = 1;`,
    `INSERT OR IGNORE INTO question_bank_releases
  (revision, question_count, enabled_count, source_sha256, published_at)
SELECT 1, COUNT(*), COALESCE(SUM(enable), 0), ${sqlValue(hash)}, CURRENT_TIMESTAMP
FROM questions;`,
    `INSERT INTO question_audit_logs
  (revision, question_id, action, before_json, after_json, actor, created_at)
SELECT 1, NULL, 'seed', NULL,
  ${sqlValue(JSON.stringify({ sourceSha256: hash, total: questions.length, enabled }))},
  'system', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM question_audit_logs WHERE action = 'seed');`,
  );

  return {
    sql: `${statements.join('\n\n')}\n`,
    hash,
    total: questions.length,
    enabled,
  };
}

function readOutputArg(): string {
  const argument = process.argv.find(value => value.startsWith('--output='));
  return argument ? path.resolve(ROOT, argument.slice('--output='.length)) : DEFAULT_OUTPUT;
}

async function main(): Promise<void> {
  const outputPath = readOutputArg();
  const raw = fs.readFileSync(DEFAULT_INPUT, 'utf8');
  const result = buildQuestionBankSeedSql(raw);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, result.sql);
  console.log(
    JSON.stringify({
      event: 'question_bank_seed_generated',
      output: path.relative(ROOT, outputPath),
      sourceSha256: result.hash,
      total: result.total,
      enabled: result.enabled,
    }),
  );
}

const entryPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (import.meta.url === entryPath) {
  main().catch(error => {
    console.error(error instanceof Error ? error.message : 'Question-bank seed generation failed');
    process.exitCode = 1;
  });
}
